import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/providers/providers";
import { geistMono, interTight, urbanist } from "@/styles/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					interTight.variable,
					urbanist.variable,
					geistMono.variable,
					"antialiased",
				)}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
