import type { Metadata } from "next";
import "@/styles/globals.css";
import { Providers } from "@/providers/providers";
import { geistMono, geistSans } from "@/styles/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
